export const countriesType = Object.freeze({
    GET_COUNTRIES_REQUEST: "GET_COUNTRIES_REQUEST",
    GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
    GET_COUNTRIES_FAILED: "GET_COUNTRIES_FAILED",
});
