export const covidType = Object.freeze({
  GET_COVID_DATA_REQUEST: "GET_COVID_DATA_REQUEST",
  GET_COVID_DATA_SUCCESS: "GET_COVID_DATA_SUCCESS",
  GET_COVID_DATA_FAILED: "GET_COVID_DATA_FAILED",
  GET_COVID_DATA_SUMMARY_SUCCESS: "GET_COVID_DATA_SUMMARY_SUCCESS",
  GET_COVID_DATA_SUMMARY_FAILED: "GET_COVID_DATA_SUMMARY_FAILED",
  POST_NEW_WEEKLY_REPORT_REQUEST: "POST_NEW_WEEKLY_REPORT_REQUEST",
  POST_NEW_WEEKLY_REPORT_SUCCESS: "POST_NEW_WEEKLY_REPORT_SUCCESS",
  POST_NEW_WEEKLY_REPORT_FAILED: "POST_NEW_WEEKLY_REPORT_FAILED",
  CLEAR_BACKOFFICE: "CLEAR_BAKCOFFICE"
});
